version: '3.8'

services:
  web:
    build: .
    container_name: php-basic
    ports:
      - "8077:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3377:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: